from PQ import PriorityQueue

pq = PriorityQueue()

'''
pq.insert_or_update(0,"A")
pq.insert_or_update(1,"A")
pq.insert_or_update(3,"A")
pq.insert_or_update(4,"A")
pq.insert_or_update(4,"B")

pq.__str__()
print(" ")
'''



pq.insert_or_update(89,"A")
pq.insert_or_update(77,"B")
pq.insert_or_update(1,"C")
pq.insert_or_update(712,"D")
pq.insert_or_update(2,"E")
pq.insert_or_update(15,"F")
pq.insert_or_update(66,"G")
pq.insert_or_update(2,"H")
pq.insert_or_update(3,"I")
pq.insert_or_update(1,"j")
pq.insert_or_update(47,"K")
pq.insert_or_update(6,"j")
pq.insert_or_update(8,"A")
pq.insert_or_update(78,"B")
pq.insert_or_update(0,"C")
pq.insert_or_update(7,"X")
pq.insert_or_update(12,"Y")
pq.insert_or_update(63,"Z")


pq.__str__()
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")

print("Inicio")
print(" ")
print(pq.extract())
pq.print_tree()
print(" ")
pq.__str__()
print(" ")
print("Fin")
print(" ")


